pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout the latest code from the repository
                git branch: 'main', url: 'https://github.com/DivijaSistla/weather-app.git'
            }
        }

        stage('Build') {
            steps {
                // Build the Docker image
                script {
                    dockerImage = docker.build("weather-app:latest")
                }
            }
        }

       stage('Deploy') {
    steps {
        script {
            def containerName = "weather-app-container"
            def runningContainer = sh(script: "docker ps -q -f name=${containerName}", returnStdout: true).trim()

            // Stop and remove the running container if it exists
            if (runningContainer) {
                sh "docker stop ${runningContainer}"
                sh "docker rm ${runningContainer}"
            }

            // Run a new container
            sh "docker run -d --name ${containerName} -p 5000:5000 weather-app:latest"
        }
    }
}

    }

    post {
        always {
            // Clean up Docker images to save space (optional)
            sh "docker image prune -f"
        }
    }
}
