pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout the latest code from the repository
                git branch: 'main', 'https://github.com/DivijaSistla/weather-app.git'
            }
        }

        stage('Build') {
            steps {
                // Build the Docker image
                script {
                    dockerImage = docker.build("weather-app:latest")
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    // Define the container name
                    def containerName = "weather-app-container"

                    // Check if the container is running
                    def runningContainer = sh(script: "docker ps -q -f name=${containerName}", returnStdout: true).trim()

                    // Stop and remove the existing container if it exists
                    if (runningContainer) {
                        sh "docker stop ${runningContainer}"
                        sh "docker rm ${runningContainer}"
                    }

                    // Run the new container
                    sh "docker run -d --name ${containerName} -p 5000:5000 weather-app:latest"
                }
            }
        }
    }

    post {
        always {
            // Clean up Docker images to save space (optional)
            sh "docker image prune -f"
        }
    }
}
